name: Digital Marketing Professors
favicon: null
layout_spectrum: 0.1475549468304962
typography_spectrum: 0.3740850230678916
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7836399590596557
  lightness: 0.9585075045470148
  saturation: 0.900153165217489
  rhythmicContrast: 0.9048121580854058
purpose: []
